#!/usr/bin/env python3
"""生成 packages/go/tts/melophone_table.go（Go 端中文 g2p 查表数据）。

数据源（均随模型/许可落仓）：
  - pypinyin（MIT）：单字最常用读音（Style.TONE3，neutral_tone_with_five）——
    多音字取最常见读，无上下文/变调（一二三 sandhi 未移植，见 ADR-0008 局限）；
  - melo/text/opencpop-strict.txt（随 MeloTTS-Chinese MIT 仓库分发）：拼音→音素串；
  - weights/config.json：symbols 表（ONNX 图 n_vocab 的唯一真源）。

过滤：去调拼音必须命中 opencpop-strict 键集，否则不入表（运行时按 UNK 读出，
不崩溃不静默吞字——G0「不吞字」的可观测失败面）。

用法：python3 tools/tts/gen_melo_phoneme_table.py
"""

import json
import os

from pypinyin import lazy_pinyin, Style

MELLO_ROOT = os.environ.get("MELOTTS_ROOT", "/root/workspace/datasets/models/melotts-zh")
OPENCMAP = os.path.join(MELLO_ROOT, "MeloTTS", "melo", "text", "opencpop-strict.txt")
CONFIG = os.path.join(MELLO_ROOT, "weights", "config.json")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "..", "packages", "go", "tts", "melophone_table.go")


def main():
    pinyin2phones = {}
    with open(OPENCMAP, encoding="utf-8") as f:
        for line in f:
            parts = line.strip().split("\t")
            if len(parts) != 2:
                continue
            pinyin2phones[parts[0]] = parts[1]

    with open(CONFIG, encoding="utf-8") as f:
        symbols = json.load(f)["symbols"]

    entries = []
    skipped = 0
    from pypinyin import pinyin as pypinyin_pinyin
    for cp in range(0x3400, 0xA000):  # CJK 扩展A + 基本区
        ch = chr(cp)
        res = pypinyin_pinyin(ch, neutral_tone_with_five=True, style=Style.TONE3,
                              errors="ignore")
        if not res or not res[0]:
            skipped += 1
            continue
        py = res[0][0]
        if py[-1].isdigit():
            tone, base = py[-1], py[:-1]
        else:  # 无调（罕见）→ 跳过，避免静默声调错位
            skipped += 1
            continue
        if base not in pinyin2phones or tone not in "12345":
            skipped += 1
            continue
        entries.append((cp, py))

    buf = []
    buf.append("// Code generated by tools/tts/gen_melo_phoneme_table.py; DO NOT EDIT.")
    buf.append("//")
    buf.append("// 数据源：pypinyin（MIT，单字最常用读音）× MeloTTS-Chinese opencpop-strict.txt")
    buf.append("// （MIT，拼音→音素）× weights/config.json symbols（ONNX n_vocab 真源）。")
    buf.append(f"// 字符 {len(entries)} 条（CJK 0x3400-0x9FFF 内命中者），跳过 {skipped} 条（读音不在 opencpop 键集/无调）。")
    buf.append("// 多音字取最常见读、无变调（sandhi 未移植）——局限与红线见 ADR-0008。")
    buf.append("")
    buf.append("package tts")
    buf.append("")
    buf.append("// meloSymbols 官方 MeloTTS-Chinese 音素表（config.json symbols，索引=token id）。")
    buf.append("var meloSymbols = []string{")
    for s in symbols:
        buf.append(f'\t"{s}",')
    buf.append("}")
    buf.append("")
    buf.append("// meloPinyinPhones 拼音 → 音素串（opencpop-strict，空格分隔）。")
    buf.append("var meloPinyinPhones = map[string]string{")
    for py, ph in sorted(pinyin2phones.items()):
        buf.append(f'\t"{py}": "{ph}",')
    buf.append("}")
    buf.append("")
    buf.append("// meloCharPinyin 单字 → 带调拼音（TONE3，末位数字=声调，5=轻声）。")
    buf.append("var meloCharPinyin = map[rune]string{")
    for cp, py in entries:
        buf.append(f"\t0x{cp:04X}: \"{py}\",")
    buf.append("}")

    with open(os.path.abspath(OUT), "w", encoding="utf-8") as f:
        f.write("\n".join(buf) + "\n")
    print(f"wrote {os.path.abspath(OUT)}: {len(entries)} chars, "
          f"{len(pinyin2phones)} pinyin, {len(symbols)} symbols")


if __name__ == "__main__":
    main()
